services:
  redis:
    image: redis:8
    restart: always

    ports:
      - "6379:6379"

    command:
      - redis-server
      - --appendonly
      - "yes"
      - --requirepass
      - ${REDIS_PASSWORD}

    volumes:
      - redis_data:/data

    networks:
      - dokploy-network

volumes:
  redis_data:
  
networks:
  dokploy-network:
    external: true
